### ISSUE TITLE
User Story - Initial Setup

### ISSUE THREAD

**Issue by uzza1hossain** [uzza1hossain/dj-commerce#1]
As a **Developer*, I can **setup dev environment**, so that **I can  start development**

### Tasks

- [x] Task 1 - Install require dependencies
- [x] Task 2 -  Create a requirements.txt file to maintain packages
- [x] Task 3 -  Create Django projects.
- [x] Task 4 -  Create Users App.
