### ISSUE TITLE
User Story - Information sections 

### ISSUE THREAD

**Issue by uzza1hossain** [uzza1hossain/dj-commerce#13]
As a Site **Owner**, I would like **the site to fulfil its purpose**, so that **it is easy to use for users and provides business benefits**

### Tasks

- [ ] Taks 1 - Create about us page.
- [ ] Task 2 - Create blog post page.
- [ ] Task 3 - Create Privacy, Terms and Condition Page.
- [ ] Task 4 - Create return/refund page.
