### ISSUE TITLE
User Story - User Profile

### ISSUE THREAD

**Issue by uzza1hossain** [uzza1hossain/dj-commerce#2]
As a **User**, I would like **to be able to create and maintain an account**, so that **I  can order products quickly and easily without having to enter information each time**

### Tasks

- [ ] Task 1 - Create User Profile / Account
- [ ] Task 2 - Edit User Profile / Account
- [ ] Task 3 - View User Profile / Account
- [ ] Task 4 - Delete User Profile / Account
