### ISSUE TITLE
User Story - Product Management

### ISSUE THREAD

**Issue by uzza1hossain** [uzza1hossain/dj-commerce#3]
As a **Site Owner**, I would like **employees to be able to manage the products on the site easily**, so that **it is easy to keep the site upto date**

### Tasks

- [ ] Task 1 - Add products
- [ ] Task 2 - Edit Products
- [ ] Task 3 - Delete Products
- [ ] Task 4 - Order Status Changes
