### ISSUE TITLE
User Story - Product Viewing

### ISSUE THREAD

**Issue by uzza1hossain** [uzza1hossain/dj-commerce#5]
As a **User**, I would like **to be able to view different levels of product information**, so that **I can select which amount of detail I want**

### Tasks

- [ ] Task 1 - View full product details
- [ ] Task 2 - View a small product card with summary information
- [ ] Task 3 - Search for a product
- [ ] Task 4 - View products by category
- [ ] Task 5 - View multiple images of a product
