### ISSUE TITLE
User Story - Shopping Cart

### ISSUE THREAD

**Issue by uzza1hossain** [uzza1hossain/dj-commerce#7]
As a **User**, I would like **to be able to add/remove products to my shopping cart**, so that **I can control the list products I am going to purchase**

### Tasks

- [ ] Task 1 - Add product to cart
- [ ] Task 2 - Delete products from cart
- [ ] Task 3 - View the products in my cart
- [ ] Task 4 - Proceed to checkout
- [ ] Task 5 - Save cart for later
