### ISSUE TITLE
User Story - Checkout

### ISSUE THREAD

**Issue by uzza1hossain** [uzza1hossain/dj-commerce#8]
As a **User**, I would like **to be able to purchase the items I have selected**, so that **I may place my order**

### Tasks

- [ ] Tasks 1 - Capture delivery and billing address
- [ ] Tasks 2 - Save address to profile
- [ ] Tasks 3 - Create an account for unregistered users
- [ ] Tasks 4 - Login if registered and return to cart
- [ ] Tasks 5 - Capture payment details
- [ ] Tasks 6 - Authorise payment
- [ ] Tasks 7 - Order confirmation email
- [ ] Tasks 7 - Order confirmation page
- [ ] Tasks 9 - Order number generation
